### ISSUE TITLE
Problem mit TWOPASS und classiclaeder

### ISSUE THREAD

**Issue by Slayer1000** [hausen8/EasyProbe#1]
Wenn man die Funktion TWOPASS nutz gibt folgende Fehlermeldung:

Shared memory conflict or RT component not loaded!
FEHLER CLASSICLADDER-   SPS Fehler bei Speicher Reservierung

Die SPS Datei kann nicht geladen werden. 
Mann kann dann die SPS Datei über das Menu nachladen.

Ich habe die Hal Files in meine Integriert damit ich TWOPASS nicht benötige. 
Damit ist das Problem weg.

**Comment by hausen8** [comment]
Danke für den Hinweis. Ich frage mal im LinuxCNC-Forum, ob das ein bekanntes Problem ist. Wir werden ja nicht die ersten sein, die TWOPASS nutzen. Wenn ich Feedback habe, gebe ich Dir hier Bescheid.
