### ISSUE TITLE
Backlash net

### ISSUE THREAD

**Issue by GTCLive** [hausen8/EasyProbe#2]
Hi, Tilman

First off thank you for this probe UI, I've been looking everywhere for a **simple but highly effective** probe interface. Yours is by far the best compared to other utterly complex UIs out there, most of which are written to enable thousand things that can go wrong!!

I'm opening this because I'm losing the BACKLASH = 0.xx feature within my *.INI. My installation went perfectly fine other than that. 

The workaround is to comment out the two lines below. However I do not know what they represent. 

Do we need these two lines at all? I don't see any ref in the project for them. What are they for?

# ---------- Switching backslash values ----------
###net   x-backlash               motion.analog-out-00         =>    ini.0.backlash
###net   y-backlash               motion.analog-out-01         =>    ini.1.backlash

**Comment by hausen8** [comment]
Hi,

I'm sorry, we simply left these lines in the postgui hal file accidently. Just remove them. We will upload a corrected version later this day.
