### ISSUE TITLE
Question about how to leave the probe-mode

### ISSUE THREAD

**Issue by throgh** [hausen8/EasyProbe#3]
Hey, thanks for this nice addon: Works like a charm on my LinuxCNC-installation (AntiX, LinuxCNC v2.8). I have just one question: How to leave the probe when all is done and finished? Perhabs I have overseen that. Would be nice to have a short answer about.

Thanks!

**Comment by hausen8** [comment]
What basically happens, when you click one of the 3 probe tool buttons, is a tool change. When you finish your probe task, you will go on with any other milling tool. The tool change command lets the machine know about it. There is nothing else to do.
